# For resetting the db in testingSET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS WaitList;
DROP TABLE IF EXISTS CheckOut;
DROP TABLE IF EXISTS BookAuthor;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS MemberAcc;
DROP TABLE IF EXISTS EmployeeAcc;
DROP TABLE IF EXISTS AppAccount;
DROP TABLE IF EXISTS Volume;
DROP TABLE IF EXISTS Series;
DROP TABLE IF EXISTS DigitalBook;
DROP TABLE IF EXISTS PhysicalBook;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Publisher;

SET FOREIGN_KEY_CHECKS = 1;
